# Generated by Django 3.1.5 on 2021-01-28 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_park', '0003_auto_20210127_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedUserCarPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('car_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_park_saved_car_parks', to='car_park.carpark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_saved_car_parks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
