# Generated by Django 3.1.5 on 2021-01-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0005_auto_20210128_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='carpark',
            name='categories',
            field=models.ManyToManyField(related_name='car_parks', to='car_park.Category'),
        ),
    ]
